  version: '3'

  services:
    # vscode:
    #   image: test_vscode

    vscode:
      # build: .
      image: vscode-docker
      volumes:
        - .:/home/coder/code-server
      ports:
        - "8443:8080"
      # environment:
      #   - POSTGRES_DB=postgres
      #   - POSTGRES_USER=postgres
      #   - POSTGRES_PASSWORD=postgres